%md

<h1>Segunda entrega - Proyecto de Procesamiento de datos a gran escala - Bono Redes Neuronales</h1>

<h2>Fecha: 26/05/2024</h2>


<h4>Programas</h4>
<h5>Ciencia de datos e Ingeniería de Sistemas</h5>
<h4>Integrantes</h4>
<p>Santiago Botero Pacheco</p>
<p>Santiago Rueda Pineda</p>
<p>Santiago Avilés Tibocha</p>
<p>Brayan Steven Carrillo Mora</p>
<p style = 'text-align:center;'>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Javeriana.svg/1200px-Javeriana.svg.png" height="200" width="300">
</p>

## Cargar Entorno para desarrollo de Red Neuronal

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("C:\\Users\\santi\\Downloads\\export(1).csv")
df.head(5)

edad  educacion  sexo  horas_trabajadas  estado_civil  condado  \
0    31       22.0     2                60           6.0        2   
1    63       22.0     2                60           1.0        3   
2    65       19.0     1                 0           1.0        3   
3    68        1.0     1                40           1.0        2   
4    63        1.0     2                40           1.0        2   

   ingresos_pre_impuestos                                           features  
0               127650.22  [6,1,0,0,2800000040,6,0,403f000000000000,40000...  
1               346479.19  [6,1,0,0,2800000040,6,0,404f800000000000,40000...  
2               346479.19  [6,1,0,0,2800000040,6,0,4050400000000000,3ff00...  
3               155003.84  [6,1,0,0,2800000040,6,0,4051000000000000,3ff00...  
4               155003.84  [6,1,0,0,2800000040,6,0,404f800000000000,40000...

## Pre-procesamiento de los datos

In [4]:
#Eliminar columnas no necesarias (Las que venian ensambladas de Databricks)
df = df.drop(columns=["features"])
df.head(5)

edad  educacion  sexo  horas_trabajadas  estado_civil  condado  \
0    31       22.0     2                60           6.0        2   
1    63       22.0     2                60           1.0        3   
2    65       19.0     1                 0           1.0        3   
3    68        1.0     1                40           1.0        2   
4    63        1.0     2                40           1.0        2   

   ingresos_pre_impuestos  
0               127650.22  
1               346479.19  
2               346479.19  
3               155003.84  
4               155003.84

In [5]:
#Seleccionar datos como parametros y label
X = df[["edad", "sexo", "horas_trabajadas", "estado_civil", "condado", "ingresos_pre_impuestos"]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_df = pd.DataFrame(X_scaled, columns=X.columns)
X_df.head(5)

edad      sexo  horas_trabajadas  estado_civil   condado  \
0 -0.452526  0.935827          1.822473      1.143639 -0.661725   
1  1.013480  0.935827          1.822473     -1.029887  0.174688   
2  1.105105 -1.068573         -1.009794     -1.029887  0.174688   
3  1.242543 -1.068573          0.878384     -1.029887 -0.661725   
4  1.013480  0.935827          0.878384     -1.029887 -0.661725   

   ingresos_pre_impuestos  
0                0.117694  
1                1.738490  
2                1.738490  
3                0.320294  
4                0.320294

In [6]:
#Crear los datos
X_data = X_df.values
Y_data = df[["educacion"]].values
print(X_data)
print("##############################################################")
print(Y_data)

[[-0.45252613  0.93582719  1.82247325  1.14363873 -0.66172468  0.11769409]
 [ 1.01347988  0.93582719  1.82247325 -1.02988717  0.17468763  1.73848968]
 [ 1.10510525 -1.06857336 -1.0097941  -1.02988717  0.17468763  1.73848968]
 ...
 [-0.63577689 -1.06857336  1.11440641  1.14363873  1.84751226 -0.34753423]
 [ 0.69279106 -1.06857336  1.11440641 -1.02988717  1.84751226 -0.34753423]
 [ 0.60116569  0.93582719 -1.0097941  -1.02988717  1.84751226 -0.34753423]]
##############################################################
[[22.]
 [22.]
 [19.]
 ...
 [21.]
 [21.]
 [21.]]


In [7]:
from sklearn.model_selection import train_test_split

# Separar los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size=0.2, random_state=42)
print(f"Datos de entrenamiento {len(X_train)}")

Datos de entrenamiento 52932


## Crear Arquitectura de la Red Neuronal

In [8]:
from keras.models import Sequential
from keras.layers import Dense

# Definir la arquitectura de la red neuronal
model = Sequential()
model.add(Dense(units=64, activation='relu', input_shape=(X_data.shape[1],)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='linear'))

# Compilar el modelo
model.compile(optimizer='adam', loss='mean_squared_error')

# Entrenar el modelo
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1, validation_data=(X_test, y_test))

Epoch 1/100


c:\Users\santi\Documents\Javeriana\Semestre_8\Emergentes\Proyecto\Geo-CNN\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1655/1655 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 80.5193 - val_loss: 15.6769
Epoch 2/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 15.6152 - val_loss: 15.3534
Epoch 3/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 15.3401 - val_loss: 14.9717
Epoch 4/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 15.0189 - val_loss: 15.0071
Epoch 5/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 986us/step - loss: 14.8047 - val_loss: 14.7545
Epoch 6/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 952us/step - loss: 15.0623 - val_loss: 14.7765
Epoch 7/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 14.7042 - val_loss: 14.7376
Epoch 8/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 14.9014 - val_loss: 14.7264
Epoch 9/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 14.6593 - val_loss: 14.6293
Epoch 10/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 14.7064 - val_loss: 14.6339
Epoch 11/100
1655/1655 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 14.4342 - val_loss: 14.6161
Epoch

## Metricas del Modelo

### Metricas del modelo NN

In [9]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = model.predict(X_test)

# Calcular las métricas
accuracy = accuracy_score(y_test, y_pred.round())
precision = precision_score(y_test, y_pred.round(), average='macro')
recall = recall_score(y_test, y_pred.round(), average='macro')
f1 = f1_score(y_test, y_pred.round(), average='macro')

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

414/414 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step
Accuracy: 0.21
Precision: 0.33
Recall: 0.25
F1-score: 0.27


c:\Users\santi\Documents\Javeriana\Semestre_8\Emergentes\Proyecto\Geo-CNN\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


### Metricas de Regresóon

In [10]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

414/414 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step
MSE: 14.519832862252699


In [11]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(X_test)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("RMSE:", rmse)

414/414 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step
RMSE: 3.810489845446737


c:\Users\santi\Documents\Javeriana\Semestre_8\Emergentes\Proyecto\Geo-CNN\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [12]:
from sklearn.metrics import r2_score
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

414/414 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step
R-squared: 0.6037395841757774


## Arquitectura del modelo

In [15]:
from tensorflow.keras.utils import plot_model

plot_model(model, to_file='model_architecture.png', show_shapes=True, show_layer_names=True)

AttributeError: module 'pydot' has no attribute 'InvocationException'